version: '3.2'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
      - /var/www/html/docker
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    restart: always
  
  php:
    container_name: php-app
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/var/www/html
      - /var/www/html/docker
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: always
  
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: '9596'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '9596'
      MYSQL_DATABASE: 'app'
    ports:
      - "3306:3306"
    volumes:
      - app:/var/lib/mysql
    restart: always
  
volumes:
  app: {}